#!/usr/bin/env bash

#
# Process:
#
# Copy the code into the packaged directory
# Run production steps required to build the app (e.g Run composer, deploy scripts, etc)
# Pull down the env-prod file from AWS S3 bucket to set relevant environment variables for the CI server
# Build new Docker images with the application baked into the images
# Remove the contents of the packaged directory
#

# Bail out on first error
set -e

# Get the directory of the build script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Get the current git commit sha
HASH=$(git rev-parse HEAD)

# Package the app
cd $DIR/../
# "archive" gives us useful tools - we can use .gitattributes
# to `export-ignore` extraneous files
git archive --format=tar --worktree-attributes $HASH | tar -xf -  -C $DIR/app/packaged

# Production Build Steps
## (Decision between export-ignore'ing docker/develop command or not)
cd $DIR/app/packaged
./sd-develop composer install --no-dev
# ./develop yarn install
# ./develop gulp --production

# Get the CI .env file
## This assumes we're running in Jenkins as user "jenkins"
/var/lib/jenkins/.venv/bin/aws s3 cp s3://sd-secrets/env-prod .env --region eu-west-2

# Build the Docker image with latest code
cd $DIR/app

docker build \
    -t localhost:5000/dockerized-app/app:latest \
    -t localhost:5000/dockerized-app/app:$HASH .

docker push localhost:5000/dockerized-app/app:latest
docker push localhost:5000/dockerized-app/app:$HASH

# Clean up packaged directory
cd $DIR/app/packaged
PWD=$(pwd)
if [ "$PWD" == "$DIR/app/packaged" ]; then
    # The "vendor" directory (any any built assets!) will be owned
    # as user "root" on the Linux file system
    # So we'll use Docker to delete them with a one-off container
    docker run --rm -w /opt -v $(pwd):/opt ubuntu:16.04 bash -c "rm -rf ./* && rm -rf ./.git* && rm .env*"
    touch .gitkeep
fi